# Generated by Django 3.1.8 on 2025-06-14 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('manager', 'Manager')], default='customer', max_length=10),
        ),
        migrations.AddField(
            model_name='userbankaccount',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('frozen', 'Frozen')], default='pending', max_length=10),
        ),
    ]
